# Generated by Django 5.0.2 on 2025-02-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0002_remove_scoresheet_fieldtext_scoresheet_field22_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='penalties',
            new_name='otherpenalties',
        ),
        migrations.RemoveField(
            model_name='scoresheet',
            name='field18',
        ),
        migrations.RemoveField(
            model_name='scoresheet',
            name='field19',
        ),
        migrations.RemoveField(
            model_name='scoresheet',
            name='field20',
        ),
        migrations.RemoveField(
            model_name='scoresheet',
            name='field21',
        ),
        migrations.RemoveField(
            model_name='scoresheet',
            name='field22',
        ),
        migrations.RemoveField(
            model_name='scoresheet',
            name='field23',
        ),
        migrations.RemoveField(
            model_name='scoresheet',
            name='field24',
        ),
        migrations.AddField(
            model_name='judge',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Lead'), (2, 'Technical'), (3, 'General'), (4, 'Journal')], null=True),
        ),
        migrations.AddField(
            model_name='judge',
            name='runpenalties',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='cluster_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teams',
            name='judge_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teams',
            name='organizer_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='judge',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mapscoresheettoteamjudge',
            name='sheetType',
            field=models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Runpenalties'), (5, 'Otherpenalties')]),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='sheetType',
            field=models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Runpenalties'), (5, 'Otherpenalties')]),
        ),
    ]
