# Generated by Django 5.0.2 on 2025-02-19 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0003_rename_penalties_judge_otherpenalties_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emdcbackend.teams')),
            ],
        ),
    ]
