# Generated by Django 5.0.2 on 2025-02-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0004_specialaward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialaward',
            name='team',
        ),
        migrations.AddField(
            model_name='specialaward',
            name='teamid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
